backend:
  name: auth0   # au lieu de git-gateway
  auth0_domain: "dev-ko2v3nq7vuzwes4u.us.auth0.com" # remplace par ton domaine Auth0
  auth0_client_id: "2xVAKz1NDbPUsZtx8sixgDbn3WxsMKpw"      # remplace par ton client ID Auth0

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "chevaux"
    label: "Chevaux"
    folder: "content/chevaux"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "title", widget: "string" }
      - { label: "Race", name: "race", widget: "string" }
      - { label: "Robe", name: "coat", widget: "string" }
      - { label: "Prix", name: "price", widget: "number" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Photo", name: "image", widget: "image" }

  - name: "legumes"
    label: "Légumes"
    folder: "content/legumes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "title", widget: "string" }
      - { label: "Prix (USD/kg)", name: "price", widget: "number" }
      - { label: "Quantité dispo", name: "stock", widget: "number" }
      - { label: "Photo", name: "image", widget: "image" }
      - { label: "Notes", name: "body", widget: "text" }
