backend:
  name: git-gateway
  branch: main   # si ton repo est en master, remplace par 'master'

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "test"
    label: "Test Collection"
    folder: "content/test"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
